org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.2
minecraft_version_range=[1.21.2]
neo_version=21.2.38
loader_version_range=[1,)

mod_id=celestialarmor
mod_name=Celestial Armor
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=fr.itsnotm33.celestialarmor
